name: base
channels:
dependencies:
   - setuptools
   - numpy
   - Cython
   - llvmlite
   - sympy
   - matplotlib
   - ipyvolume
   - ipython
   - voila
   - pip
   - pip:
     - -r requirements.txt
     #- "--editable=git+https://github.com/birnstiel/diskwarp.git#egg=diskwarp"