name: base
channels:
dependencies:
   - python>=3.7
   - setuptools
   - numpy
   - sympy
   - matplotlib
   - ipyvolume
   - ipython
   - jupyter
   - voila
   - pip
   - ipympl
   - gfortran
   - pip:
     - "--editable=git+https://github.com/birnstiel/diskwarp.git#egg=diskwarp"
     #- git+https://github.com/birnstiel/diskwarp.git