name: base
channels:
dependencies:
   - python>=3.7
   - setuptools
   - numpy
   - sympy
   - matplotlib
   - ipyvolume
   - ipython
   - jupyter
   - voila
   - pip
   - gcc_linux-64
   - gfortran_linux-64
   - pip:
     - -r requirements.txt
     #- "--editable=git+https://github.com/birnstiel/diskwarp.git#egg=diskwarp"