name: base
channels:
  - conda-forge
dependencies:
  - ipyvolume
  - ipywidgets >=7.6.0,<8
  - voila
  - voila-material
  - python>=3.7
  - setuptools
  - numpy
  - sympy
  - matplotlib
  - ipympl
  - pip
  - gfortran
  - pip:
    - "--editable=git+https://github.com/birnstiel/diskwarp.git#egg=diskwarp"
    #- git+https://github.com/birnstiel/diskwarp.git